version: "3.3"

services:
  api:
    image: registry.gitlab.com/ravimosharksas/apis/contract/app-nodejs/${API_BASE:-alpine}:${API_VERSION:-latest}
    environment:
      SWAGGER_HOST: ${SWAGGER_HOST:-localhost:3000}
      SWAGGER_BASE_PATH: ${SWAGGER_BASE_PATH:-/api/}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PORT: ${APP_PORT:-8000}
    ports:
      - "${APP_PORT:-3000}:3000"
